# --- MONGODB ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeName: master-node-01
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo

---
# --- BACKEND API ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeName: master-node-01
      containers:
      - name: backend
        image: 172.16.0.202:5000/cv-backend:latest
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/cvbuilder"
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        - name: ALLOWED_ORIGINS
          value: "https://cv-builder.skirshta.fr,http://100.120.92.90:30000,http://152.228.130.229:30000,http://vps-82ecffcd.vps.ovh.net:30000,http://172.16.0.202:30000"
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: RESEND_API_KEY
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001 

---
# --- FRONTEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  # ON GARDE 2 RÉPLICAS POUR LE FRONTEND
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 172.16.0.202:5000/cv-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

## ADMINER

---
# --- ADMINER AVEC MONGO SUPPORT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        # Cette version est plus complète pour les drivers
        image: adminer:4.8.1
        ports:
        - containerPort: 8080
        env:
        - name: ADMINER_DEFAULT_SERVER
          value: "mongo"
        # Note: Adminer lui-même ne gère pas le login "admin/admin123" pour l'interface
        # Il gère le login vers la base de données. 
        # Pour protéger l'accès à l'interface, on utilise Nginx (voir étape 2).
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
