FROM jenkins/jenkins:lts

USER root

# Installation du client Docker
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*
# ... (après apt-get install git docker.io)
RUN git config --global --add safe.directory '*'

# Ajout de l'utilisateur jenkins au groupe docker
# Note : On force souvent l'ID du groupe pour matcher celui de l'hôte si besoin
RUN usermod -aG docker jenkins

USER jenkins
